-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/05/19 11:16:41 PM
-- Server version: 5.5.5-10.3.12-MariaDB-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';
--
INSERT INTO asig_roles VALUES
(5, 1, 1, '2019-03-18 14:12:10', '0000-00-00 00:00:00'),
(6, 2, 2, '2019-03-18 17:12:27', '2019-03-18 17:12:27'),
(7, 3, 6, '2019-03-18 17:30:59', '2019-03-18 17:30:59'),
(8, 48, 6, '2019-05-06 03:19:30', '2019-05-06 03:19:30');